package samuraisword.game;

public enum GamePhase {
	LOBBY, ASSIGN, RECOVERY, DRAW, MAIN, ATTACK, DISCARD, PARADA, GRITODEBATALLA, JIUJITSU, DISCARDARM, DISCARDPLAYER, RESPIRACION, DISCARDOTHER, BUSHIDO, DISCARTRED, AVISO
}
